[main]

[sources.gelbooru]
tags = ["1girl", "dross"]

[outputs.discord]
webhooks = [
    "https://discordapp.com/api/webhooks/940959386891849788/csT0Sait5f59ZCZ7WE9i-zckUz-_LiM9vlkocm6IoJ88-1dtkpnegNgnWT2B1hc2Lwu0"
]

[outputs.dummy]
